// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TINYORACLE_STAGEATINY_H_
#define FLATBUFFERS_GENERATED_TINYORACLE_STAGEATINY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace StageATiny {

struct Leaf;
struct LeafBuilder;

struct AliasRoot;
struct AliasRootBuilder;

struct StringRoot;
struct StringRootBuilder;

struct VectorRoot;
struct VectorRootBuilder;

struct Leaf FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LeafBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_PAYLOAD = 6
  };
  int32_t key() const {
    return GetField<int32_t>(VT_KEY, 0);
  }
  bool KeyCompareLessThan(const Leaf * const o) const {
    return key() < o->key();
  }
  int KeyCompareWithValue(int32_t _key) const {
    return static_cast<int>(key() > _key) - static_cast<int>(key() < _key);
  }
  int64_t payload() const {
    return GetField<int64_t>(VT_PAYLOAD, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_KEY, 4) &&
           VerifyField<int64_t>(verifier, VT_PAYLOAD, 8) &&
           verifier.EndTable();
  }
};

struct LeafBuilder {
  typedef Leaf Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(int32_t key) {
    fbb_.AddElement<int32_t>(Leaf::VT_KEY, key, 0);
  }
  void add_payload(int64_t payload) {
    fbb_.AddElement<int64_t>(Leaf::VT_PAYLOAD, payload, 0);
  }
  explicit LeafBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Leaf> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Leaf>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Leaf> CreateLeaf(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t key = 0,
    int64_t payload = 0) {
  LeafBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_key(key);
  return builder_.Finish();
}

struct Leaf::Traits {
  using type = Leaf;
  static auto constexpr Create = CreateLeaf;
};

struct AliasRoot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AliasRootBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEFT = 4,
    VT_RIGHT = 6,
    VT_ALIAS_LEFT = 8
  };
  const StageATiny::Leaf *left() const {
    return GetPointer<const StageATiny::Leaf *>(VT_LEFT);
  }
  const StageATiny::Leaf *right() const {
    return GetPointer<const StageATiny::Leaf *>(VT_RIGHT);
  }
  const StageATiny::Leaf *alias_left() const {
    return GetPointer<const StageATiny::Leaf *>(VT_ALIAS_LEFT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LEFT) &&
           verifier.VerifyTable(left()) &&
           VerifyOffset(verifier, VT_RIGHT) &&
           verifier.VerifyTable(right()) &&
           VerifyOffset(verifier, VT_ALIAS_LEFT) &&
           verifier.VerifyTable(alias_left()) &&
           verifier.EndTable();
  }
};

struct AliasRootBuilder {
  typedef AliasRoot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_left(::flatbuffers::Offset<StageATiny::Leaf> left) {
    fbb_.AddOffset(AliasRoot::VT_LEFT, left);
  }
  void add_right(::flatbuffers::Offset<StageATiny::Leaf> right) {
    fbb_.AddOffset(AliasRoot::VT_RIGHT, right);
  }
  void add_alias_left(::flatbuffers::Offset<StageATiny::Leaf> alias_left) {
    fbb_.AddOffset(AliasRoot::VT_ALIAS_LEFT, alias_left);
  }
  explicit AliasRootBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AliasRoot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AliasRoot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AliasRoot> CreateAliasRoot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<StageATiny::Leaf> left = 0,
    ::flatbuffers::Offset<StageATiny::Leaf> right = 0,
    ::flatbuffers::Offset<StageATiny::Leaf> alias_left = 0) {
  AliasRootBuilder builder_(_fbb);
  builder_.add_alias_left(alias_left);
  builder_.add_right(right);
  builder_.add_left(left);
  return builder_.Finish();
}

struct AliasRoot::Traits {
  using type = AliasRoot;
  static auto constexpr Create = CreateAliasRoot;
};

struct StringRoot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringRootBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HOT = 4,
    VT_COLD = 6,
    VT_HOT_ALIAS = 8
  };
  const ::flatbuffers::String *hot() const {
    return GetPointer<const ::flatbuffers::String *>(VT_HOT);
  }
  const ::flatbuffers::String *cold() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COLD);
  }
  const ::flatbuffers::String *hot_alias() const {
    return GetPointer<const ::flatbuffers::String *>(VT_HOT_ALIAS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HOT) &&
           verifier.VerifyString(hot()) &&
           VerifyOffset(verifier, VT_COLD) &&
           verifier.VerifyString(cold()) &&
           VerifyOffset(verifier, VT_HOT_ALIAS) &&
           verifier.VerifyString(hot_alias()) &&
           verifier.EndTable();
  }
};

struct StringRootBuilder {
  typedef StringRoot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_hot(::flatbuffers::Offset<::flatbuffers::String> hot) {
    fbb_.AddOffset(StringRoot::VT_HOT, hot);
  }
  void add_cold(::flatbuffers::Offset<::flatbuffers::String> cold) {
    fbb_.AddOffset(StringRoot::VT_COLD, cold);
  }
  void add_hot_alias(::flatbuffers::Offset<::flatbuffers::String> hot_alias) {
    fbb_.AddOffset(StringRoot::VT_HOT_ALIAS, hot_alias);
  }
  explicit StringRootBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringRoot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringRoot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringRoot> CreateStringRoot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> hot = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cold = 0,
    ::flatbuffers::Offset<::flatbuffers::String> hot_alias = 0) {
  StringRootBuilder builder_(_fbb);
  builder_.add_hot_alias(hot_alias);
  builder_.add_cold(cold);
  builder_.add_hot(hot);
  return builder_.Finish();
}

struct StringRoot::Traits {
  using type = StringRoot;
  static auto constexpr Create = CreateStringRoot;
};

inline ::flatbuffers::Offset<StringRoot> CreateStringRootDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *hot = nullptr,
    const char *cold = nullptr,
    const char *hot_alias = nullptr) {
  auto hot__ = hot ? _fbb.CreateString(hot) : 0;
  auto cold__ = cold ? _fbb.CreateString(cold) : 0;
  auto hot_alias__ = hot_alias ? _fbb.CreateString(hot_alias) : 0;
  return StageATiny::CreateStringRoot(
      _fbb,
      hot__,
      cold__,
      hot_alias__);
}

struct VectorRoot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectorRootBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEYED = 4,
    VT_VALUES = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StageATiny::Leaf>> *keyed() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StageATiny::Leaf>> *>(VT_KEYED);
  }
  const ::flatbuffers::Vector<int32_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_VALUES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEYED) &&
           verifier.VerifyVector(keyed()) &&
           verifier.VerifyVectorOfTables(keyed()) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct VectorRootBuilder {
  typedef VectorRoot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_keyed(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StageATiny::Leaf>>> keyed) {
    fbb_.AddOffset(VectorRoot::VT_KEYED, keyed);
  }
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> values) {
    fbb_.AddOffset(VectorRoot::VT_VALUES, values);
  }
  explicit VectorRootBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VectorRoot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VectorRoot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VectorRoot> CreateVectorRoot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StageATiny::Leaf>>> keyed = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> values = 0) {
  VectorRootBuilder builder_(_fbb);
  builder_.add_values(values);
  builder_.add_keyed(keyed);
  return builder_.Finish();
}

struct VectorRoot::Traits {
  using type = VectorRoot;
  static auto constexpr Create = CreateVectorRoot;
};

inline ::flatbuffers::Offset<VectorRoot> CreateVectorRootDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    std::vector<::flatbuffers::Offset<StageATiny::Leaf>> *keyed = nullptr,
    const std::vector<int32_t> *values = nullptr) {
  auto keyed__ = keyed ? _fbb.CreateVectorOfSortedTables<StageATiny::Leaf>(keyed) : 0;
  if (values) { _fbb.ForceVectorAlignment(values->size(), sizeof(int32_t), 16); }
  auto values__ = values ? _fbb.CreateVector<int32_t>(*values) : 0;
  return StageATiny::CreateVectorRoot(
      _fbb,
      keyed__,
      values__);
}

inline const StageATiny::AliasRoot *GetAliasRoot(const void *buf) {
  return ::flatbuffers::GetRoot<StageATiny::AliasRoot>(buf);
}

inline const StageATiny::AliasRoot *GetSizePrefixedAliasRoot(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<StageATiny::AliasRoot>(buf);
}

inline const char *AliasRootIdentifier() {
  return "FBLT";
}

inline bool AliasRootBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, AliasRootIdentifier());
}

inline bool SizePrefixedAliasRootBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, AliasRootIdentifier(), true);
}

template <bool B = false>
inline bool VerifyAliasRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<StageATiny::AliasRoot>(AliasRootIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedAliasRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<StageATiny::AliasRoot>(AliasRootIdentifier());
}

inline void FinishAliasRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StageATiny::AliasRoot> root) {
  fbb.Finish(root, AliasRootIdentifier());
}

inline void FinishSizePrefixedAliasRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StageATiny::AliasRoot> root) {
  fbb.FinishSizePrefixed(root, AliasRootIdentifier());
}

}  // namespace StageATiny

#endif  // FLATBUFFERS_GENERATED_TINYORACLE_STAGEATINY_H_
