// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WITNESS_STAGEAFLATBUFFERSWITNESS_H_
#define FLATBUFFERS_GENERATED_WITNESS_STAGEAFLATBUFFERSWITNESS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace StageAFlatBuffersWitness {

struct Child;
struct ChildBuilder;

struct Root;
struct RootBuilder;

struct Child FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChildBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4
  };
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           verifier.EndTable();
  }
};

struct ChildBuilder {
  typedef Child Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(Child::VT_X, x, 0);
  }
  explicit ChildBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Child> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Child>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Child> CreateChild(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0) {
  ChildBuilder builder_(_fbb);
  builder_.add_x(x);
  return builder_.Finish();
}

struct Child::Traits {
  using type = Child;
  static auto constexpr Create = CreateChild;
};

struct Root FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RootBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEFT = 4,
    VT_RIGHT = 6
  };
  const StageAFlatBuffersWitness::Child *left() const {
    return GetPointer<const StageAFlatBuffersWitness::Child *>(VT_LEFT);
  }
  const StageAFlatBuffersWitness::Child *right() const {
    return GetPointer<const StageAFlatBuffersWitness::Child *>(VT_RIGHT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LEFT) &&
           verifier.VerifyTable(left()) &&
           VerifyOffset(verifier, VT_RIGHT) &&
           verifier.VerifyTable(right()) &&
           verifier.EndTable();
  }
};

struct RootBuilder {
  typedef Root Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_left(::flatbuffers::Offset<StageAFlatBuffersWitness::Child> left) {
    fbb_.AddOffset(Root::VT_LEFT, left);
  }
  void add_right(::flatbuffers::Offset<StageAFlatBuffersWitness::Child> right) {
    fbb_.AddOffset(Root::VT_RIGHT, right);
  }
  explicit RootBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Root> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Root>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Root> CreateRoot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<StageAFlatBuffersWitness::Child> left = 0,
    ::flatbuffers::Offset<StageAFlatBuffersWitness::Child> right = 0) {
  RootBuilder builder_(_fbb);
  builder_.add_right(right);
  builder_.add_left(left);
  return builder_.Finish();
}

struct Root::Traits {
  using type = Root;
  static auto constexpr Create = CreateRoot;
};

inline const StageAFlatBuffersWitness::Root *GetRoot(const void *buf) {
  return ::flatbuffers::GetRoot<StageAFlatBuffersWitness::Root>(buf);
}

inline const StageAFlatBuffersWitness::Root *GetSizePrefixedRoot(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<StageAFlatBuffersWitness::Root>(buf);
}

template <bool B = false>
inline bool VerifyRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<StageAFlatBuffersWitness::Root>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<StageAFlatBuffersWitness::Root>(nullptr);
}

inline void FinishRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StageAFlatBuffersWitness::Root> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StageAFlatBuffersWitness::Root> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace StageAFlatBuffersWitness

#endif  // FLATBUFFERS_GENERATED_WITNESS_STAGEAFLATBUFFERSWITNESS_H_
